### PR TITLE
removed login and signup, remove old CSV dependency, switched to JSON

### LINKED ISSUE #47: remove Login for good and replace with JSON
currently, login was altered to allow one user instead of being completely removed.

as a result of this issue,
1. login / signup will be removed forever
2. a user.json fill will exist in the root directory
3. a parser will read from this json and construct the necessary nested data structures
4. all code will rely on the new structure defined by the DAO using JSON
5. user will incorporate a Builder design strategy to allow for direct building using the parsed data

### PR DESCRIPTION
**Pull request by awesominat**
in this PR, I've

1. removed login and signup
2. removed the concept of "Users" and replaced it with "User" as the application will only house one user. that means all hash maps mapping username to user are now just a singular User entity that loads in data from user.json
3. remove CSV as we have a lot of nested data structures, making the data file incredibly unreadable and especially unnecessary if it's only one user
4. added JSON saving using GSON
5. added LocalDate type adapters as LocalDate has private, inaccessible variables, messing up how GSON works
6. added TransactionDeserializer as Transaction is an abstract class and it's unclear, from GSON's perspective, if the user's transaction is a Buy/Sell/Topup
7. altered all test files and most app files to follow new structure

PR fixes and closes #47 and #6

### CODE REVIEW

**Comment by awesominat** [comment]
the tests fail because the new code references DashboardViewModel, a class not found in HEAD of main

**Review by rickypramanick — COMMENTED** [review]
I think that the changes look sound and these can be tested further upon its integration to the main branch. I was looking at the logginInTesting file, and I see the test is commented out, so would we need to write a new test for it or is the commented out section valid. Furthermore, I was wondering as to why we switched to JSON from CSV? I understand from your comments that there were a lot of dependencies in the old CSV format however, it is not so clear as to how the implementation of the JSON format to store transaction history helps in this case.

**Comment by awesominat** [comment]
good point about the logging in app file. it seems I forgot to remove it.

to address your other concerns:
1. We switched from CSV to JSON because we now only support 1 user. Previously, if we had multiple users, we could store them each on a new line alongside their history and portfolio. To do that, we would have had to encode the history and portfolio into JSON anyway. However, this is unreadable as the JSON will be squeezed onto one line without formatting.
2. Since we now only support one user, we can get rid of the CSV + JSON hybrid storage and switch to just JSON, this also gives us the freedom to look at the JSON file without it all being on one line as it's by default prettified to be on multiple lines.
3. There were not a lot of dependencies in the old CSV.
4. The data structures we support are nested pretty deep. Take the history, its a hash map of strings mapping to TransactionHistory, which contains a Stock and a List of Transactions. Transactions contain PricePoint. This adds an unprecedented amount of depth to the data structures, which would have been a headache to read through the squeezed CSV file to debug and future issues.

I hope these addressed your concerns

**Review by rickypramanick — APPROVED** [review]
Yep thanks for the clarification, all looks and sounds good.

**Pull request merged**
