### PR TITLE
Test for GetNews - DO NOT APPROVE

### PR DESCRIPTION
**Pull request by quiz3**
I added a test for GetNews. I'm not sure how effective it is or if it tests much at all but it certainly tests some parts of the code and most importantly, the tests pass!

Unfortunately, the maven tests do not pass. Don't approve!

### CODE REVIEW

**Comment by awesominat** [comment]
The maven tests pass because you are trying to actually call our API instead of mocking it or using a "dummy" API.

please reference buySellTest.java to see how to mock the APIAccessInterface

```
APIAccessInterface mockApi = Mockito.mock(APIAccessInterface.class);
        Mockito.when(mockApi.getCurrentPrice("AAPL")).thenReturn(new PricePoint(LocalDate.now(), 100.0));
        Mockito.when(mockApi.getCompanyProfile("AAPL")).thenReturn(new CompanyInformation("US",
                "Apple Inc", "AAPL", "https://www.apple.com/", "1980-12-12"));
        Mockito.when(mockApi.getLastMonthPrices("AAPL")).thenReturn(lastMonthPrices);
```

to explain it simply, Mockito.when(mockApi.method()).thenReturn(new something) basically says that if any class tries to call the API's `method`, then intercept the call and manually return `new something`

**Comment by quiz3** [comment]
> The maven tests fail because you are trying to actually call our API instead of mocking it or using a "dummy" API.
> 
> please reference buySellTest.java to see how to mock the APIAccessInterface
> 
> ```
> APIAccessInterface mockApi = Mockito.mock(APIAccessInterface.class);
>         Mockito.when(mockApi.getCurrentPrice("AAPL")).thenReturn(new PricePoint(LocalDate.now(), 100.0));
>         Mockito.when(mockApi.getCompanyProfile("AAPL")).thenReturn(new CompanyInformation("US",
>                 "Apple Inc", "AAPL", "https://www.apple.com/", "1980-12-12"));
>         Mockito.when(mockApi.getLastMonthPrices("AAPL")).thenReturn(lastMonthPrices);
> ```
> 
> to explain it simply, Mockito.when(mockApi.method()).thenReturn(new something) basically says that if any class tries to call the API's `method`, then intercept the call and manually return `new something`

OOOhhhhhhh. I did reference `buySellTest.java` in the creation of the test. However, I did not understand what the when and then statements were saying. This was very helpful, I now know what to do to follow.

**Review by quiz3 — COMMENTED** [review]
These tests need to get fixed. I did not understand how to use the when and then and the mock features of the testing. I tried to mimic the buySellTest but failed to do so effectively. This will require revision in the future. For the time being, it is not as pressing as implementing other essential parts of the application.

**Comment by gursi26** [comment]
can this be deleted or is it still being worked on

**Pull request closed without merging**
