### PR TITLE
Improvements to DashboardView

### PR DESCRIPTION
**Pull request by quiz3**

### CODE REVIEW

**Comment by quiz3** [comment]
NOTE: Once the reviewer merges this branch, I would ask them to kindly go to PR #103 and follow the instructions found therein.

**Review by awesominat — COMMENTED** [review]
I accidentally asked this in the other PR, but can you briefly explain why so many view models need to be passed in the dashboard view ?

**Comment by quiz3** [comment]
> can you briefly explain why so many view models need to be passed in the dashboard view ?

Yes. The reason why so many view models need to be passed to the dashboard view is because the dashboard view is the Home Screen, and thus needs the ability to switch to the various other screens of our app. Without the view models of the other Views, the dashboard view would not be able to switch the user to a different view upon the pressing of a button. For example, if the user presses the Buy button, the dashboard view needs to transfer them to the `BuyView`.

**Review by awesominat — APPROVED** [review]
great

**Pull request merged**
